### ISSUE TITLE
What is "Paused" in Preferences

### ISSUE THREAD

**Issue by exoego** [girigiribauer/fly-free#22]
## Outline 📝

Both Twitter (X) and Bluesky have two on/off toggles.

<img width="567" alt="image" src="https://github.com/girigiribauer/fly-free/assets/127635/c2f0bb29-a88b-4d72-91e1-4e30f7c3a80c">

## Why do you need to do it?

I assume the top-right one is to disable/enable each site.
However, I do not get it what "paused" is meant to.

**Comment by girigiribauer** [comment]
I want to fix issues that don't work rather than improving the UI/UX.
